services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack-dev
    environment:
      - SERVICES=s3,rds,lambda,apigateway,sqs,elasticache,logs
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
      - "4571:4571"
    volumes:
      - ./localstack/scripts:/etc/localstack/scripts
      - ./localstack/trivia_api:/var/task
      - ./localstack/scripts/setup/setup.sh:/etc/localstack/init/ready.d/setup.sh
      - /var/run/docker.sock:/var/run/docker.sock