spring:
  datasource:
    url: jdbc:postgresql://localhost.localstack.cloud:4510/dundermifflin
    username: test
    password: test
  jpa:
    show-sql: true

aws:
  region: ${AWS_DEFAULT_REGION:eu-west-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  s3:
    bucket: dunder-mifflin-bucket
    endpoint: http://localhost:4566
  elasticache:
    host: localhost.localstack.cloud
    port: 4511
  sqs:
    endpoint: http://sqs.eu-west-1.localhost.localstack.cloud:4566
    queue: /000000000000/quotes

trivia-api:
  endpoint: http://localhost:4566/restapis/j9n3xmavvf/test/_user_request_/trivia
